# RULES DEFINED THROUGH COOPERATIVE GAMES

  # Private game:           mcstGamePrivate
  # Kar rule:               mcstKar
  # Irreducible game:       mcstGameIrred
  # Optimistic game:        mcstGameOpt
  # Public game:            mcstGamePublic
  # Cycle-complete game:    mcstGameCC


#### Private Game ####

#' Cost Allocations based on the Private Game for MCSTP
#'
#' @description
#' This function computes the cost allocation for the private or pessimistic game (Bird, 1976)
#' associated with a minimum cost spanning tree problem \eqn{(N_0, C)}, using a specified solution concept.
#' The private game, denoted as \eqn{(N, v_C^p)} \eqn{(}or simply
#' \eqn{(N, v^p)}\eqn{)}, evaluates the cost of each coalition \eqn{S \subseteq N} under the assumption
#' that agents outside the coalition are not available to provide their nodes
#' as intermediaries.
#'
#' @details
#' The private game \eqn{(N, v_C^p)} is a cooperative game with
#' transferable utility (TU game) defined for each coalition
#' \eqn{S \subseteq N} as:
#'
#' \deqn{v_C^p(S) = m(S_0, C),}
#'
#' where \eqn{m(S_0, C)} is the cost of the minimum spanning tree of the
#' subproblem induced by the agents in \eqn{S} and the source.
#' This approach is termed "private" or "pessimistic" because the nodes in
#' \eqn{N \setminus S} belong to these agents, and their participation
#' is needed in order to use their nodes.
#'
#' When the Shapley value (\code{sol = "shapley"}) is applied to this game,
#' the resulting allocation is known as Kar's rule (Kar, 2002). For a function
#' that particularizes this specific case, see \code{\link{mcstKar}}.
#'
#' Under \code{method = "exact"}, the function builds the full characteristic
#' function (all \eqn{2^n - 1} values). Depending on the chosen solution concept,
#' it computes the allocation via \code{\link[CoopGame]{shapleyValue}} (which
#' relies on the coalition-based formula) or \code{\link[CoopGame]{nucleolus}}.
#'
#' For larger networks, \code{method = "montecarlo"} provides an approximation
#' of the Shapley value through random sampling using \eqn{n_{sim}} permutations. This approach
#' implements lazy evaluation based on the permutation formula of the Shapley value:
#' instead of computing the MST cost for all \eqn{2^n - 1}
#' possible subsets, it only evaluates the specific subcoalitions generated by
#' the random permutations.
#'
#' This is highly useful when the number of agents is large,
#' as it significantly reduces memory usage and computation time while providing a
#' very accurate approximation of Kar's rule. For networks with few players, the
#' exact method is preferred to avoid potential overestimations.
#'
#' For more details on these formulas, see \code{\link{mcstRules}}.
#'
#' @param C cost matrix between nodes. Accepts multiple formats (see
#' "Supported formats for \code{C}" below).
#' @param sol character; the solution concept to apply. Options are \code{"shapley"}
#' (default), or \code{"nucleolus"} (only for \code{method = "exact"}).
#' @param draw logical; if \code{TRUE}, plots the network highlighting an optimal
#' tree in red (constructed using Prim's algorithm), indicating the cost allocated to
#' each agent in brackets below the node. For \eqn{n \le 3} and \code{method = "exact"},
#' it also displays the optimal network for each subcoalition \eqn{S \subset N}.
#' @param which.plot character string indicating which plots to display. If \code{"details"} (only
#' for \eqn{n \le 3} and \code{method = "exact"}), displays the optimal network for each subcoalition
#' \eqn{S \subset N}; if \code{"main"}, the allocation for \eqn{N} is plotted.
#' Default is \code{c("main", "details")}.
#' @param titles logical; if \code{TRUE} (default), adds a main title
#' specifying the cooperative game and a subtitle with the solution concept, method
#' (exact or Monte Carlo) and the total network cost.
#' @param method character string specifying the calculation method. If \code{"exact"}
#' (default), computes the exact allocation (Shapley value or nucleolus) and the full characteristic function; if \code{"montecarlo"}, estimates
#' an approximation of the Shapley value through random sampling using \code{nsim} permutations. It uses lazy
#' evaluation to avoid computing all possible coalitions (recommended
#' for large networks).
#' @param nsim integer; the number of permutations to sample when using
#' \code{method = "montecarlo"}. Default is 10,000.
#'
#' @section Supported formats for \code{C}:
#'
#' Note: In all cases, \code{Inf} is accepted for disconnected node pairs. The first
#' row/column is assumed to be the source node (0).
#'
#' The function accepts the following formats for the cost input:
#'
#' \describe{
#'   \item{Numeric vector}{The lower triangle of a symmetric cost matrix, excluding the diagonal.
#'   Length must be \eqn{n(n+1)/2}, where \eqn{n} is the number of agents (excluding the source).}
#'
#'   \item{Square matrix / Data frame}{A standard adjacency matrix where \code{C[i, j]}
#'   represents the cost between node \eqn{i} and node \eqn{j}.}
#'
#'   \item{Edge list (matrix or data frame)}{An alternative to the full matrix.
#'   It must contain columns named \code{"from"} and \code{"to"},
#'   plus a third column for the weights/costs.}
#'
#'   \item{'igraph' object}{A weighted undirected graph. See the \code{\link[igraph:igraph-package]{igraph}}
#'   package for details on creating these objects.}
#'
#'   \item{File path}{A string pointing to a \code{.csv}, \code{.xlsx}, or \code{.xls} file.
#'   The file can contain either a square matrix (without headers) or an edge list
#'   (with \code{"from"} and \code{"to"} headers).}
#' }
#'
#' @note
#' The private game is a strong reference for stability.
#' Classical rules such as Bird, Dutta-Kar, or the folk rule are known to belong
#' to the core of \eqn{v^p} for any MCST problem. As a result, these
#' allocations are coalitionally stable under the pessimistic cost perspective.
#'
#' Although the Shapley value and the nucleolus are well-established solution
#' concepts, it has been proven that computing both for this game is NP-hard.
#'
#' @return A list containing:
#' \itemize{
#'    \item \code{coalitions}: a character vector representing all possible coalitions \eqn{S \subseteq N}, ordered by cardinality. If \code{method = "montecarlo"}, returns a string indicating that lazy evaluation was used.
#'    \item \code{v_p}: a numeric vector containing the characteristic function values \eqn{v^p(S)} for all coalitions. If \code{method = "montecarlo"}, returns a string indicating that lazy evaluation was used.
#'    \item \code{contributions}: a data frame with the marginal contributions for the sampled permutations. If \code{method = "exact"}, returns a string indicating that this table is not used.
#'    \item \code{allocation}: a numeric vector containing the computed cost allocation for each agent.
#'    \item \code{total}: the total cost of the MCST, \eqn{v^p(N)}.
#'    \item \code{nperms}: the number of permutations \code{nsim} used in the calculation. If \code{method = "exact"}, returns a string indicating that it was not computed.
#'    \item \code{percentage}: the share of the total cost allocated to each agent.
#'    \item \code{ranking}: ranking of agents by cost (from highest to lowest; ties marked with *).
#'    \item \code{method}: the method used for the calculation (\code{"exact"} or \code{"montecarlo"}).
#'    \item \code{sol}: the solution concept used (\code{"shapley"} or \code{"nucleolus"}).
#'    }
#'
#' @seealso
#' \code{\link{mcstBird}}, \code{\link{mcstDuttaKar}}, \code{\link{mcstFolk}}
#' for classical rules belonging to the core of \eqn{v^p}.
#'
#' \code{\link{mcstKar}} for the specific cost allocation rule based on the
#' Shapley value of this game.
#'
#' \code{\link{mcstGameIrred}}, \code{\link{mcstGameCC}} for the pessimistic games
#' based on the irreducible cost matrix \eqn{\bar{C}} and the cycle-complete cost matrix \eqn{C^*}, respectively.
#'
#' \code{\link{mcstGameOpt}}, \code{\link{mcstGamePublic}} for optimistic alternatives to the private approach.
#'
#' \code{\link{mcstRules}} for an overview of the available rules and analysis tools in the package.
#'
#' @references
#' Bergantiños G, Vidal-Puga J (2021) A review of cooperative rules
#' and their associated algorithms for minimum-cost spanning tree problems.
#' SERIEs, 12:73-100
#'
#' Bird C (1976) On cost allocation for a spanning tree: a game theoretic
#' approach. Networks 6(4):335–350
#'
#' Kar A (2002) Axiomatization of the Shapley value on minimum cost
#' spanning tree games. Games Econom Behav 38(2):265–277
#'
#' @examples
#' # Simple vector input
#' mcstGamePrivate(c(12, 15, 20, 4, 6, 8), sol = "shapley", draw = TRUE)
#'
#' # Input with infinite costs (disconnected nodes)
#' C_inf <- c(5, 9, Inf, 15, 6, Inf, 7, Inf, Inf, Inf,
#'            Inf, 8, 7, Inf, Inf, 5, Inf, Inf, 8, 9, 11)
#' mcstGamePrivate(C_inf, sol = "nucleolus")
#'
#' # Matrix input
#' C_mat <- matrix(c(0, 12, 15, 12,
#'                  12,  0,  4,  6,
#'                  15,  4,  0,  8,
#'                  12,  6,  8,  0), byrow = TRUE, ncol = 4)
#' mcstGamePrivate(C_mat, draw = TRUE, which.plot = "main", titles = FALSE)
#'
#' @concept Cooperative Games
#' @concept MCSTP
#'
#' @export

mcstGamePrivate <- function(C, sol = c("shapley", "nucleolus"), draw = FALSE, which.plot = c("main", "details"), titles = TRUE, method = c("exact", "montecarlo"), nsim = 10000) {

  # Convert input into a standard cost matrix C for N_0 (agents + source)
  C_mat <- .prepare_matrix(C)
  n <- nrow(C_mat) - 1  # Number of agents n = |N|

  sol <- match.arg(sol)
  method <- match.arg(method)
  which.plot <- match.arg(which.plot, several.ok = TRUE)

  # Check if Monte Carlo is actually necessary
  if (sol == "shapley" && method == "montecarlo" && (2^n - 1) <= nsim) {
    message("Warning: (2^n - 1) <= nsim. Consider using method = 'exact' for maximum efficiency")
  }

  # Performance validation
  if (sol == "shapley" && method == "exact" && n > 20) {
    message("Warning: n > 20. Consider using method = 'montecarlo' to reduce processing time")
  }

  if (method == "montecarlo" && sol == "nucleolus") {
    stop("The solution '", sol, "' is only available for method = 'exact'")
  }

  if (sol == "nucleolus" && n > 15) {
    warning("Computing the nucleolus for n > 15 can be extremely slow and memory-intensive")
  }


  ## Execution ##

  if (method == "exact") { # Exact

    if (!requireNamespace("CoopGame", quietly = TRUE)) {
      stop("Package 'CoopGame' required for the exact method. Please install it.")
    }

    # Build the characteristic function v^p(S) using binary indexing
    ncoals <- 2^n - 1

    vvals <- vapply(1:ncoals, function(i) {
      # Decode binary index i to find members of coalition S
      S <- which(as.logical(intToBits(i)[1:n]))
      sub_idx <- c(1, S + 1) # Include the source (0)

      # Compute MST cost for this specific subset
      .get_cost(C_mat[sub_idx, sub_idx, drop = FALSE])
    }, numeric(1))

    # Generate all possible coalitions ordered by cardinality for final output
    coalitions <- unlist(lapply(1:n, function(k) combn(n, k, simplify = FALSE)), recursive = FALSE)
    coals_names <- sapply(coalitions, function(S) paste0("{", paste(S, collapse = ","), "}"))
    coals_names[length(coals_names)] <- "N"

    idx <- sapply(coalitions, function(S) sum(2^(S - 1)))
    values <- vvals[idx]
    m_cost <- vvals[ncoals] # Total cost v^p(N)

    # Calculate the allocation based on the chosen solution concept
    if (sol == "shapley") {
      value <- CoopGame::shapleyValue(values)

    } else if (sol == "nucleolus") {
      # Define savings game: v_s(S) = sum(v(i)) - v(S)
      v_s <- sapply(1:ncoals, function(i) {
        S <- which(as.logical(intToBits(i)[1:n]))
        sum(vvals[2^(S - 1)]) - vvals[i]
      })

      # Compute nucleolus of the savings game
      nuc_s <- try(CoopGame::nucleolus(v_s), silent = TRUE)

      if (inherits(nuc_s, "try-error") || is.null(nuc_s)) {
        value <- rep(NA, n)
      } else {
        # Convert savings back to costs: x_i = v(i) - savings_i
        v_ind <- vvals[2^(1:n - 1)]
        value <- v_ind - nuc_s
      }
    }

    names(value) <- as.character(1:n)
    results <- list(value = value, nperms = "Not computed")

  } else { # Monte Carlo (lazy evaluation)

    if (sol == "shapley") {
      # Skip full characteristic function for efficiency
      coals_names <- "Not computed (Lazy Monte Carlo)"
      values <- "Not computed (Lazy Monte Carlo)"
      m_cost <- .get_cost(C_mat)

      # Initialize objects
      perms <- matrix(nrow = nsim, ncol = n)
      contributions <- matrix(0, nrow = nsim, ncol = n, dimnames = list(NULL, as.character(1:n)))

      for (p in 1:nsim) {
        pi <- sample(1:n)
        perms[p, ] <- pi
        predecessors <- c()
        v_old <- 0

        for (i in pi) {
          predecessors <- c(predecessors, i)
          sub_idx <- c(1, predecessors + 1)
          v_new <- .get_cost(C_mat[sub_idx, sub_idx, drop = FALSE])
          contributions[p, i] <- v_new - v_old
          v_old <- v_new
        }
      }

      # Results
      results <- list(
        value = colMeans(contributions),
        contributions = data.frame(pi = apply(perms, 1, paste, collapse = "-"),
                                   contributions, check.names = FALSE),
        nperms = nsim
      )
    }
  }


  ## Visualization ##

  if (draw) {

    show_details <- "details" %in% which.plot
    show_main <- "main" %in% which.plot

    if (n > 1 && n <= 3 && show_details && method == "exact") {

      rows <- if(n == 3) 2 else 1
      cols <- if(n == 3) 3 else 2
      old_par <- par(mfrow = c(rows, cols), oma = c(0, 0, if(titles) 5 else 0, 0))
      on.exit(par(old_par), add = TRUE)

      for (i in 1:(ncoals - 1)) {
        S <- coalitions[[i]]
        sub_idx <- c(1, S + 1)

        C_inf <- matrix(Inf, nrow = n + 1, ncol = n + 1, dimnames = list(0:n, 0:n))

        C_inf[sub_idx, sub_idx] <- C_mat[sub_idx, sub_idx]
        sub_C <- C_mat[sub_idx, sub_idx, drop = FALSE]
        arcs_S <- .get_arcs(sub_C)

        .plot_mcstp(C_inf, arcs_S, NULL,
                    main_title = "", sub_title = paste0("S = {", paste(S, collapse=","), "}"), show_stage = FALSE) #   |  v^p(S): ", round(values[i], 2)
      }

      if (titles) {
        mtext("MCST for each subcoalition S",
              side = 3, line = 1.5, cex = 1.2, font = 2, outer = TRUE)
        mtext("Private Game (N, v^p)  |  Method: exact", side = 3, line = 0.1, cex = 0.7, family = "sans", font = 3,
              col = "#444444", outer = TRUE) # paste0("Private Game  |  Total Cost v^p(N): ", round(m_cost, 2))
      }

      par(old_par)
    }

    if (n > 1 && n <= 3 && show_details && show_main && method == "exact") {
      devAskNewPage(TRUE)
      on.exit(devAskNewPage(FALSE), add = TRUE)
    }

    if (show_main) {
      arcs_N <- .get_arcs(C_mat)
      tit <- if(titles) "Private Game (N, v^p)" else ""
      lab <- if (method == "exact") {"exact"} else {"Monte Carlo"}
      sol_name <- paste0(toupper(substr(sol, 1, 1)), substr(sol, 2, nchar(sol)))
      sub_tit <- if(titles) paste0("Solution: ", sol_name, "  |  Method: ", lab, "  |  Total Cost v^p(N): ", round(m_cost, 2)) else ""
      .plot_mcstp(C_mat, arcs_N, results$value,
                  main_title = tit, sub_title = sub_tit, show_stage = FALSE)
    }
  }

  # Generates a ranking based on allocations, using stars (*) for ties
  ord <- order(-results$value, names(results$value))
  vals <- results$value[ord]; noms <- names(results$value)[ord]
  tab <- table(vals)
  rep_vals <- sort(as.numeric(names(tab[tab > 1])), decreasing = TRUE)

  rank_star <- noquote(sapply(1:length(vals), function(i) {
    if (vals[i] %in% rep_vals) {
      paste0(noms[i], strrep("*", which(rep_vals == vals[i])))
    } else noms[i]
  }))


  ## Output ##

  output <- list(
    coalitions = coals_names,
    v_p = values,
    contributions = if(method == "montecarlo") results$contributions else "Exact method does not use a contributions table",
    allocation = results$value,
    total = m_cost,
    nperms = results$nperms,
    percentage = round((results$value / m_cost) * 100, 2),
    ranking = rank_star,
    method = method,
    sol = sol
  )

  class(output) <- "mcstp_private"

  return(output)
}

#' @export
print.mcstp_private <- function(x, ...) {
  if (is.character(x$v_p)) {
    cat("Characteristic function v^p(S) not computed (Monte Carlo efficiency mode)\n")
  } else {
    v_S <- data.frame(
      S = x$coalitions,
      "v^p(S)" = x$v_p,
      row.names = NULL,
      check.names = FALSE
    )
    print(v_S)
  }

  sol_label <- paste0(toupper(substr(x$sol, 1, 1)), substr(x$sol, 2, nchar(x$sol)))
  cat("\nSolution:", sol_label, "\n")
  print(round(x$allocation, 2))
  invisible(x)
}



#### Kar's Rule ####

#' Kar's Rule for MCSTP
#'
#' This function computes Kar's rule for a minimum cost spanning tree problem \eqn{(N_0, C)}.
#' It is defined as the Shapley value of the associated private game (Kar, 2002).
#'
#' @param C cost matrix between nodes. Accepts multiple formats (see the
#' "Supported formats for \code{C}" section in \code{\link{mcstGamePrivate}}).
#' @param draw logical; if \code{TRUE}, plots the network highlighting an optimal
#' tree in red (constructed using Prim's algorithm), indicating the cost allocated to
#' each agent in brackets below the node. For \eqn{n \le 3} and \code{method = "exact"},
#' it also displays the optimal network for each subcoalition \eqn{S \subset N}.
#' @param which.plot character string indicating which plots to display. If \code{"details"} (only
#' for \eqn{n \le 3} and \code{method = "exact"}), displays the optimal network for each subcoalition
#' \eqn{S \subset N}; if \code{"main"}, the allocation for \eqn{N} is plotted.
#' Default is \code{c("main", "details")}.
#' @param titles logical; if \code{TRUE} (default), adds a main title
#' specifying the cooperative game and a subtitle with the solution concept, method
#' (exact or Monte Carlo) and the total network cost.
#' @param method character string specifying the calculation method. If \code{"exact"}
#' (default), computes the exact Shapley value allocation and the full characteristic function; if \code{"montecarlo"}, estimates
#' an approximation of the Shapley value through random sampling using \code{nsim} permutations. It uses lazy
#' evaluation to avoid computing all possible coalitions (recommended
#' for large networks).
#' @param nsim integer; the number of permutations to sample when using
#' \code{method = "montecarlo"}. Default is 10,000.
#'
#' @return A list containing the computed allocation and calculation details.
#' For a comprehensive breakdown of the elements returned in this list, see the "Value" section
#' in \code{\link{mcstGamePrivate}}.
#'
#' @note
#' For an in-depth explanation of the private game's properties, its characteristic
#' function formulation, and discussions on computational complexity, please refer
#' to the documentation for \code{\link{mcstGamePrivate}}.
#'
#' @seealso
#' \code{\link{mcstGamePrivate}} for the general pessimistic game.
#'
#' \code{\link{mcstRules}} for an overview of the available rules and analysis tools in the package.
#'
#' @references
#' Bergantiños G, Vidal-Puga J (2021) A review of cooperative rules
#' and their associated algorithms for minimum-cost spanning tree problems.
#' SERIEs, 12:73-100
#'
#' Kar A (2002) Axiomatization of the Shapley value on minimum cost
#' spanning tree games. Games Econom Behav 38(2):265–277
#'
#' @examples
#' # Simple vector input
#' mcstKar(c(12, 15, 20, 4, 6, 8), draw = TRUE)
#'
#' # Input with infinite costs (disconnected nodes)
#' C_inf <- c(5, 9, Inf, 15, 6, Inf, 7, Inf, Inf, Inf,
#'            Inf, 8, 7, Inf, Inf, 5, Inf, Inf, 8, 9, 11)
#' mcstKar(C_inf)
#'
#' # Matrix input
#' C_mat <- matrix(c(0, 12, 15, 12,
#'                  12,  0,  4,  6,
#'                  15,  4,  0,  8,
#'                  12,  6,  8,  0), byrow = TRUE, ncol = 4)
#' mcstKar(C_mat, draw = TRUE, which.plot = "main", titles = FALSE)
#'
#' @concept Cooperative Games
#' @concept MCSTP
#'
#' @export

mcstKar <- function(C, draw = FALSE, which.plot = c("main", "details"), titles = TRUE,
                    method = c("exact", "montecarlo"), nsim = 10000) {

  return(mcstGamePrivate(C = C,
                         sol = "shapley",
                         draw = draw,
                         which.plot = which.plot,
                         titles = titles,
                         method = method,
                         nsim = nsim))
}



#### Irreducible Game ####

#' Cost Allocations based on the Irreducible Game for MCSTP
#'
#' @description
#' This function computes the cost allocation for the irreducible game
#' (Bird, 1976) associated with a minimum cost spanning tree problem \eqn{(N_0, C)},
#' using a specified solution concept. The irreducible game, denoted as \eqn{(N, v_C^i)} \eqn{(}or simply
#' \eqn{(N, v^i)}\eqn{)}, is defined as the private game associated with
#' the irreducible cost matrix \eqn{\bar{C}}.
#'
#' @details
#' The irreducible game \eqn{(N, v_C^i)} is a cooperative game with
#' transferable utility (TU game) defined for each coalition
#' \eqn{S \subseteq N} as:
#'
#' \deqn{v_C^i(S) = m(S_0, \bar{C}),}
#'
#' where \eqn{m(S_0, \bar{C})} is the cost of the minimum spanning tree of the
#' subproblem induced by the agents in \eqn{S} and the source, evaluated over
#' the irreducible costs \eqn{\bar{C}}. The irreducible cost between any two nodes
#' corresponds to the maximum cost arc on the unique path connecting them in
#' the optimal tree.
#'
#' Under \code{method = "exact"}, the function builds the full characteristic
#' function (all \eqn{2^n - 1} values). Depending on the chosen solution concept,
#' it computes the allocation via \code{\link[CoopGame]{shapleyValue}} (which
#' relies on the coalition-based formula) or \code{\link[CoopGame]{nucleolus}}.
#'
#' For larger networks, \code{method = "montecarlo"} provides an approximation
#' of the Shapley value through random sampling using \eqn{n_{sim}} permutations. This approach
#' implements lazy evaluation based on the permutation formula of the Shapley value:
#' instead of computing the MST cost for all \eqn{2^n - 1}
#' possible subsets, it only evaluates the specific subcoalitions generated by
#' the random permutations.
#'
#' This is highly useful when the number of agents is large,
#' as it significantly reduces memory usage and computation time while providing a
#' very accurate approximation of the exact allocation. For networks with few players, the
#' exact method is preferred to avoid potential overestimations.
#'
#' For more details on these formulas, see \code{\link{mcstRules}}.
#'
#' @inheritParams mcstGamePrivate
#'
#' @inheritSection mcstGamePrivate Supported formats for \code{C}
#'
#' @note
#' The irreducible game is a strong reference for stability. Its core (the
#' irreducible core) is always non-empty and constitutes a subset of the core
#' of \eqn{v^p}. Classical rules such as Bird and folk are
#' known to belong to the core of \eqn{v^i}.
#'
#' It has been proven that the Shapley value of the irreducible game coincides
#' with both the \code{\link{mcstFolk}} of the original problem and \code{\link{mcstBird}} applied to
#' the irreducible costs (Bergantiños and Vidal-Puga, 2007a).
#'
#' Unlike the private game, calculating solution concepts for the irreducible
#' game is computationally efficient. Computing both the Shapley value and
#' the nucleolus of \eqn{v^i} can be done in \eqn{O(|N|^2)} time.
#'
#' @return A list containing:
#' \itemize{
#'    \item \code{coalitions}: a character vector representing all possible coalitions \eqn{S \subseteq N}, ordered by cardinality. If \code{method = "montecarlo"}, returns a string indicating that lazy evaluation was used.
#'    \item \code{C_irred}: the irreducible cost matrix \eqn{\bar{C}} associated with the MCST of the problem.
#'    \item \code{v_i}: a numeric vector containing the characteristic function values \eqn{v^i(S)} for all coalitions. If \code{method = "montecarlo"}, returns a string indicating that lazy evaluation was used.
#'    \item \code{contributions}: a data frame with the marginal contributions for the sampled permutations. If \code{method = "exact"}, returns a string indicating that this table is not used.
#'    \item \code{allocation}: a numeric vector containing the computed cost allocation for each agent.
#'    \item \code{total}: the total cost of the MCST, \eqn{v^i(N)}.
#'    \item \code{nperms}: the number of permutations \code{nsim} used in the calculation. If \code{method = "exact"}, returns a string indicating that it was not computed.
#'    \item \code{percentage}: the share of the total cost allocated to each agent.
#'    \item \code{ranking}: ranking of agents by cost (from highest to lowest; ties marked with *).
#'    \item \code{method}: the method used for the calculation (\code{"exact"} or \code{"montecarlo"}).
#'    \item \code{sol}: the solution concept used (\code{"shapley"} or \code{"nucleolus"}).
#' }
#'
#' @seealso
#' \code{\link{mcstBird}} of \eqn{(N_0, \bar{C})}, \code{\link{mcstFolk}}
#' of \eqn{(N_0, C)} for classical rules belonging to the core of \eqn{v^i}
#' that coincide with \eqn{Sh(N,v^i)}.
#'
#' \code{\link{mcstGamePrivate}}, \code{\link{mcstGamePublic}} for the pessimistic and optimistic games based on the original costs.
#'
#' \code{\link{mcstGameCC}} for the pessimistic game based on the cycle-complete cost matrix \eqn{C^*}.
#'
#' \code{\link{mcstGameOpt}} for an equivalent game under the Shapley value.
#'
#' \code{\link{mcstRules}} for an overview of the available rules and analysis tools in the package.
#'
#' @references
#' Bergantiños G, Vidal-Puga J (2007a) A fair rule in minimum cost spanning
#' tree problems. J Econom Theory 137(1):326–352
#'
#' Bergantiños G, Vidal-Puga J (2021) A review of cooperative rules
#' and their associated algorithms for minimum-cost spanning tree problems.
#' SERIEs, 12:73-100
#'
#' Bird C (1976) On cost allocation for a spanning tree: a game theoretic
#' approach. Networks 6(4):335–350
#'
#' @examples
#' # Simple vector input
#' mcstGameIrred(c(12, 15, 20, 4, 6, 8), sol = "shapley", draw = TRUE)
#'
#' # Input with infinite costs (disconnected nodes)
#' C_inf <- c(5, 9, Inf, 15, 6, Inf, 7, Inf, Inf, Inf,
#'            Inf, 8, 7, Inf, Inf, 5, Inf, Inf, 8, 9, 11)
#' mcstGameIrred(C_inf, sol = "shapley")
#'
#' # Matrix input
#' C_mat <- matrix(c(0, 12, 15, 12,
#'                  12,  0,  4,  6,
#'                  15,  4,  0,  8,
#'                  12,  6,  8,  0), byrow = TRUE, ncol = 4)
#' mcstGameIrred(C_mat, draw = TRUE, which.plot = "main", titles = FALSE)
#'
#' @concept Cooperative Games
#' @concept MCSTP
#'
#' @export

mcstGameIrred <- function(C, sol = c("shapley", "nucleolus"), draw = FALSE, which.plot = c("main", "details"), titles = TRUE, method = c("exact", "montecarlo"), nsim = 10000) {

  # Convert input into a standard cost matrix C for N_0 (agents + source)
  C_mat <- .prepare_matrix(C)
  n <- nrow(C_mat) - 1  # Number of agents n = |N|

  sol <- match.arg(sol)
  method <- match.arg(method)
  which.plot <- match.arg(which.plot, several.ok = TRUE)

  # Check if Monte Carlo is actually necessary
  if (sol == "shapley" && method == "montecarlo" && (2^n - 1) <= nsim) {
    message("Warning: (2^n - 1) <= nsim. Consider using method = 'exact' for maximum efficiency")
  }

  # Performance validation
  if (sol == "shapley" && method == "exact" && n > 20) {
    message("Warning: n > 20. Consider using method = 'montecarlo' to reduce processing time")
  }

  if (method == "montecarlo" && sol == "nucleolus") {
    stop("The solution '", sol, "' is only available for method = 'exact'")
  }

  if (sol == "nucleolus" && n > 15) {
    warning("Computing the nucleolus for n > 15 can be extremely slow and memory-intensive")
  }


  ## Execution ##

  # Compute the irreducible matrix barC
  C_irred <- .get_irreducible(C_mat)

  if (method == "exact") { # Exact

    if (!requireNamespace("CoopGame", quietly = TRUE)) {
      stop("Package 'CoopGame' required for the exact method. Please install it.")
    }

    # Build the characteristic function v^i(S) using binary indexing over barC
    ncoals <- 2^n - 1

    vvals <- vapply(1:ncoals, function(i) {
      # Decode binary index i to find members of coalition S
      S <- which(as.logical(intToBits(i)[1:n]))
      sub_idx <- c(1, S + 1) # Include the source (0)

      # Compute MST cost for this specific subset
      .get_cost(C_irred[sub_idx, sub_idx, drop = FALSE])
    }, numeric(1))

    # Generate all possible coalitions ordered by cardinality for final output
    coalitions <- unlist(lapply(1:n, function(k) combn(n, k, simplify = FALSE)), recursive = FALSE)
    coals_names <- sapply(coalitions, function(S) paste0("{", paste(S, collapse = ","), "}"))
    coals_names[length(coals_names)] <- "N"

    idx <- sapply(coalitions, function(S) sum(2^(S - 1)))
    values <- vvals[idx]
    m_cost <- vvals[ncoals] # Total cost v^i(N)

    # Calculate the allocation based on the chosen solution concept
    if (sol == "shapley") {
      value <- CoopGame::shapleyValue(values)

    } else if (sol == "nucleolus") {
      # Define savings game: v_s(S) = sum(v(i)) - v(S)
      v_s <- sapply(1:ncoals, function(i) {
        S <- which(as.logical(intToBits(i)[1:n]))
        sum(vvals[2^(S - 1)]) - vvals[i]
      })

      # Compute nucleolus of the savings game
      nuc_s <- try(CoopGame::nucleolus(v_s), silent = TRUE)

      if (inherits(nuc_s, "try-error") || is.null(nuc_s)) {
        value <- rep(NA, n)
      } else {
        # Convert savings back to costs: x_i = v(i) - savings_i
        v_ind <- vvals[2^(1:n - 1)]
        value <- v_ind - nuc_s
      }
    }

    names(value) <- as.character(1:n)
    results <- list(value = value, nperms = "Not computed")

  } else { # Monte Carlo (lazy evaluation)

    if (sol == "shapley") {
      # Skip full characteristic function for efficiency
      coals_names <- "Not computed (Lazy Monte Carlo)"
      values <- "Not computed (Lazy Monte Carlo)"
      m_cost <- .get_cost(C_irred)

      # Initialize objects
      perms <- matrix(nrow = nsim, ncol = n)
      contributions <- matrix(0, nrow = nsim, ncol = n, dimnames = list(NULL, as.character(1:n)))

      for (p in 1:nsim) {
        pi <- sample(1:n)
        perms[p, ] <- pi
        predecessors <- c()
        v_old <- 0

        for (i in pi) {
          predecessors <- c(predecessors, i)
          sub_idx <- c(1, predecessors + 1)
          v_new <- .get_cost(C_irred[sub_idx, sub_idx, drop = FALSE])
          contributions[p, i] <- v_new - v_old
          v_old <- v_new
        }
      }

      # Results
      results <- list(
        value = colMeans(contributions),
        contributions = data.frame(pi = apply(perms, 1, paste, collapse = "-"),
                                   contributions, check.names = FALSE),
        nperms = nsim
      )
    }
  }


  ## Visualization ##

  if (draw) {

    show_details <- "details" %in% which.plot
    show_main <- "main" %in% which.plot

    if (n > 1 && n <= 3 && show_details && method == "exact") {

      rows <- if(n == 3) 2 else 1
      cols <- if(n == 3) 3 else 2
      old_par <- par(mfrow = c(rows, cols), oma = c(0, 0, if(titles) 5 else 0, 0))
      on.exit(par(old_par), add = TRUE)

      for (i in 1:(ncoals - 1)) {
        S <- coalitions[[i]]
        sub_idx <- c(1, S + 1)

        C_inf <- matrix(Inf, nrow = n + 1, ncol = n + 1, dimnames = list(0:n, 0:n))

        C_inf[sub_idx, sub_idx] <- C_irred[sub_idx, sub_idx]
        sub_C <- C_irred[sub_idx, sub_idx, drop = FALSE]
        arcs_S <- .get_arcs(sub_C)

        .plot_mcstp(C_inf, arcs_S, NULL,
                    main_title = "", sub_title = paste0("S = {", paste(S, collapse=","), "}"), show_stage = FALSE) #   |  v^i(S): ", round(values[i], 2)
      }

      if (titles) {
        mtext("MCST for each subcoalition S",
              side = 3, line = 1.5, cex = 1.2, font = 2, outer = TRUE)
        mtext("Irreducible Game (N, v^i)  |  Method: exact", side = 3, line = 0.1, cex = 0.7, family = "sans", font = 3,
              col = "#444444", outer = TRUE) # paste0("Irreducible Game  |  Total Cost v^i(N): ", round(m_cost, 2))
      }

      par(old_par)
    }

    if (n > 1 && n <= 3 && show_details && show_main && method == "exact") {
      devAskNewPage(TRUE)
      on.exit(devAskNewPage(FALSE), add = TRUE)
    }

    if (show_main) {
      arcs_N <- .get_arcs(C_irred)
      tit <- if(titles) "Irreducible Game (N, v^i)" else ""
      lab <- if (method == "exact") {"exact"} else {"Monte Carlo"}
      sol_name <- paste0(toupper(substr(sol, 1, 1)), substr(sol, 2, nchar(sol)))
      sub_tit <- if(titles) paste0("Solution: ", sol_name, "  |  Method: ", lab, "  |  Total Cost v^i(N): ", round(m_cost, 2)) else ""
      .plot_mcstp(C_irred, arcs_N, results$value,
                  main_title = tit, sub_title = sub_tit, show_stage = FALSE)
    }
  }

  # Generates a ranking based on allocations, using stars (*) for ties
  ord <- order(-results$value, names(results$value))
  vals <- results$value[ord]; noms <- names(results$value)[ord]
  tab <- table(vals)
  rep_vals <- sort(as.numeric(names(tab[tab > 1])), decreasing = TRUE)

  rank_star <- noquote(sapply(1:length(vals), function(i) {
    if (vals[i] %in% rep_vals) {
      paste0(noms[i], strrep("*", which(rep_vals == vals[i])))
    } else noms[i]
  }))


  ## Output ##

  output <- list(
    coalitions = coals_names,
    C_irred = C_irred,
    v_i = values,
    contributions = if(method == "montecarlo") results$contributions else "Exact method does not use a contributions table",
    allocation = results$value,
    total = m_cost,
    nperms = results$nperms,
    percentage = round((results$value / m_cost) * 100, 2),
    ranking = rank_star,
    method = method,
    sol = sol
  )

  class(output) <- "mcstp_irred"

  return(output)
}

#' @export
print.mcstp_irred <- function(x, ...) {
  if (is.character(x$v_i)) {
    cat("Characteristic function v^i(S) not computed (Monte Carlo efficiency mode)\n")
  } else {
    v_S <- data.frame(
      S = x$coalitions,
      "v^i(S)" = x$v_i,
      row.names = NULL,
      check.names = FALSE
    )
    print(v_S)
  }

  sol_label <- paste0(toupper(substr(x$sol, 1, 1)), substr(x$sol, 2, nchar(x$sol)))
  cat("\nSolution:", sol_label, "\n")
  print(round(x$allocation, 2))
  invisible(x)
}



#### Optimistic Game ####

#' Cost Allocations based on the Optimistic Game for MCSTP
#'
#' @description
#' This function computes the cost allocation for the optimistic game
#' (Bergantiños and Vidal-Puga, 2007b) associated with a minimum cost spanning tree problem
#' \eqn{(N_0, C)}, using a specified solution concept. The optimistic game, denoted as \eqn{(N, v_C^o)} \eqn{(}or simply
#' \eqn{(N, v^o)}\eqn{)}, evaluates the cost of each coalition \eqn{S \subseteq N}
#' assuming that agents in \eqn{N \setminus S} are already connected. Thus,
#' agents in \eqn{S} can connect to the source through agents in \eqn{N \setminus S}
#' for free.
#'
#' @details
#' Let \eqn{T := N \setminus S}. The optimistic game \eqn{(N, v_C^o)} is a
#' cooperative game with transferable utility (TU game) defined for each
#' coalition \eqn{S \subseteq N} as:
#'
#' \deqn{v_C^o(S) = m(S_0, C^T),}
#'
#' where \eqn{m(S_0, C^T)} is the cost of the minimum spanning tree of the
#' subproblem induced by the agents in \eqn{S} and the source, using the
#' modified cost matrix \eqn{C^T}. In this matrix, the cost between agents
#' in \eqn{S} remains the same, i.e., \eqn{c_{ij}^T = c_{ij}} for all \eqn{i,j \in S},
#' but the cost to connect any agent \eqn{i \in S} to the source is updated as:
#'
#' \deqn{c_{0i}^T = \min_{j \in T \cup \{0\}} c_{ji}.}
#'
#' Under \code{method = "exact"}, the function builds the full characteristic
#' function (all \eqn{2^n - 1} values). Depending on the chosen solution concept,
#' it computes the allocation via \code{\link[CoopGame]{shapleyValue}} (which
#' relies on the coalition-based formula) or \code{\link[CoopGame]{nucleolus}}.
#'
#' For larger networks, \code{method = "montecarlo"} provides an approximation
#' of the Shapley value through random sampling using \eqn{n_{sim}} permutations. This approach
#' implements lazy evaluation based on the permutation formula of the Shapley value:
#' instead of computing the MST cost for all \eqn{2^n - 1}
#' possible subsets, it only evaluates the specific subcoalitions generated by
#' the random permutations.
#'
#' This is highly useful when the number of agents is large,
#' as it significantly reduces memory usage and computation time while providing a
#' very accurate approximation of the exact allocation. For networks with few players, the
#' exact method is preferred to avoid potential overestimations.
#'
#' For more details on these formulas, see \code{\link{mcstRules}}.
#'
#' @inheritParams mcstGamePrivate
#'
#' @inheritSection mcstGamePrivate Supported formats for \code{C}
#'
#' @note
#' The optimistic game associated with any MCST problem coincides with the optimistic
#' game associated with its irreducible form, i.e.,
#'
#' \deqn{v_C^o = v_{\bar{C}}^o.}
#'
#' If \eqn{(N_0, \bar{C})} is irreducible, the private and optimistic games, \eqn{v^p}
#' and \eqn{v^o}, are dual: \eqn{v^p(S) + v^o(N \setminus S) = m(N_0, C)} for all \eqn{S \subset N}.
#'
#' Furthermore, \eqn{Sh(N, v_C^o) = Sh(N, v_C^i)}, so applying the
#' Shapley value to \eqn{v^o} provides an alternative way of obtaining the
#' \code{\link{mcstFolk}} (Bergantiños and Vidal-Puga, 2007b).
#'
#' @return A list containing:
#' \itemize{
#'    \item \code{coalitions}: a character vector representing all possible coalitions \eqn{S \subseteq N}, ordered by cardinality. If \code{method = "montecarlo"}, returns a string indicating that lazy evaluation was used.
#'    \item \code{C_opt}: a list of the optimistic cost matrices \eqn{C^T} for each coalition \eqn{S \subseteq N}. If \code{method = "montecarlo"}, returns a string indicating that lazy evaluation was used.
#'    \item \code{v_o}: a numeric vector containing the characteristic function values \eqn{v^o(S)} for all coalitions. If \code{method = "montecarlo"}, returns a string indicating that lazy evaluation was used.
#'    \item \code{contributions}: a data frame with the marginal contributions for the sampled permutations. If \code{method = "exact"}, returns a string indicating that this table is not used.
#'    \item \code{allocation}: a numeric vector containing the computed cost allocation for each agent.
#'    \item \code{total}: the total cost of the MCST, \eqn{v^o(N)}.
#'    \item \code{nperms}: the number of permutations \code{nsim} used in the calculation. If \code{method = "exact"}, returns a string indicating that it was not computed.
#'    \item \code{percentage}: the share of the total cost allocated to each agent.
#'    \item \code{ranking}: ranking of agents by cost (from highest to lowest; ties marked with *).
#'    \item \code{method}: the method used for the calculation (\code{"exact"} or \code{"montecarlo"}).
#'    \item \code{sol}: the solution concept used (\code{"shapley"} or \code{"nucleolus"}).
#' }
#'
#' @seealso
#' \code{\link{mcstGamePrivate}} for a game based on a pessimistic approach.
#'
#' \code{\link{mcstGameIrred}} for an equivalent game under the Shapley value.
#'
#' \code{\link{mcstRules}} for an overview of the available rules and analysis tools in the package.
#'
#' @references
#' Bergantiños G, Vidal-Puga J (2007b) The optimistic TU game in minimum cost
#' spanning tree problems. Int J Game Theory 36(2):223–239
#'
#' Bergantiños G, Vidal-Puga J (2021) A review of cooperative rules
#' and their associated algorithms for minimum-cost spanning tree problems.
#' SERIEs, 12:73-100
#'
#' @examples
#' # Simple vector input
#' mcstGameOpt(c(12, 15, 20, 4, 6, 8), sol = "shapley", draw = TRUE)
#'
#' # Input with infinite costs (disconnected nodes)
#' C_inf <- c(5, 9, Inf, 15, 6, Inf, 7, Inf, Inf, Inf,
#'            Inf, 8, 7, Inf, Inf, 5, Inf, Inf, 8, 9, 11)
#' mcstGameOpt(C_inf, sol = "shapley")
#'
#' # Matrix input
#' C_mat <- matrix(c(0, 12, 15, 12,
#'                  12,  0,  4,  6,
#'                  15,  4,  0,  8,
#'                  12,  6,  8,  0), byrow = TRUE, ncol = 4)
#' mcstGameOpt(C_mat, draw = TRUE, which.plot = "main", titles = FALSE)
#'
#' @concept Cooperative Games
#' @concept MCSTP
#'
#' @export

mcstGameOpt <- function(C, sol = c("shapley", "nucleolus"), draw = FALSE, which.plot = c("main", "details"), titles = TRUE, method = c("exact", "montecarlo"), nsim = 10000) {

  # Convert input into a standard cost matrix C for N_0 (agents + source)
  C_mat <- .prepare_matrix(C)
  n <- nrow(C_mat) - 1  # Number of agents n = |N|

  sol <- match.arg(sol)
  method <- match.arg(method)
  which.plot <- match.arg(which.plot, several.ok = TRUE)

  # Check if Monte Carlo is actually necessary
  if (sol == "shapley" && method == "montecarlo" && (2^n - 1) <= nsim) {
    message("Warning: (2^n - 1) <= nsim. Consider using method = 'exact' for maximum efficiency")
  }

  # Performance validation
  if (sol == "shapley" && method == "exact" && n > 20) {
    message("Warning: n > 20. Consider using method = 'montecarlo' to reduce processing time")
  }

  if (method == "montecarlo" && sol == "nucleolus") {
    stop("The solution '", sol, "' is only available for method = 'exact'")
  }

  if (sol == "nucleolus" && n > 15) {
    warning("Computing the nucleolus for n > 15 can be extremely slow and memory-intensive")
  }


  ## Execution ##

  if (method == "exact") { # Exact

    if (!requireNamespace("CoopGame", quietly = TRUE)) {
      stop("Package 'CoopGame' required for the exact method. Please install it.")
    }

    # Build the characteristic function v^o(S) using binary indexing
    ncoals <- 2^n - 1

    eval_list <- lapply(1:ncoals, function(i) {
      # Decode binary index i to find members of coalition S
      S <- which(as.logical(intToBits(i)[1:n]))

      # Identify the complementary coalition T = N \ S
      T_agents <- setdiff(1:n, S)

      sub_idx <- c(1, S + 1) # Include the source (0)
      T0_idx <- c(1, T_agents + 1) # T_0

      # Standard matrix for S
      sub_C <- C_mat[sub_idx, sub_idx, drop = FALSE]

      # Modify the connection to the source for each agent in S
      # c^T_{0i} = min_{j \in T_0} c_{ji}
      min_costs <- apply(C_mat[S + 1, T0_idx, drop = FALSE], 1, min)

      # Update the sub_C matrix (symmetric)
      cols <- 2:length(sub_idx)
      sub_C[1, cols] <- min_costs
      sub_C[cols, 1] <- min_costs

      # Compute MST cost for this specific subset
      val <- .get_cost(sub_C)

      list(val = val, C_mod = sub_C)
    })

    vvals <- sapply(eval_list, `[[`, "val")
    C_T <- lapply(eval_list, `[[`, "C_mod")

    # Generate all possible coalitions ordered by cardinality for final output
    coalitions <- unlist(lapply(1:n, function(k) combn(n, k, simplify = FALSE)), recursive = FALSE)
    coals_names <- sapply(coalitions, function(S) paste0("{", paste(S, collapse = ","), "}"))
    coals_names[length(coals_names)] <- "N"

    idx <- sapply(coalitions, function(S) sum(2^(S - 1)))
    values <- vvals[idx]
    m_cost <- vvals[ncoals] # Total cost v^o(N)

    # Calculate the allocation based on the chosen solution concept
    if (sol == "shapley") {
      value <- CoopGame::shapleyValue(values)

    } else if (sol == "nucleolus") {
      # Define savings game: v_s(S) = sum(v(i)) - v(S)
      v_s <- sapply(1:ncoals, function(i) {
        S <- which(as.logical(intToBits(i)[1:n]))
        sum(vvals[2^(S - 1)]) - vvals[i]
      })

      # Compute nucleolus of the savings game
      nuc_s <- try(CoopGame::nucleolus(v_s), silent = TRUE)

      if (inherits(nuc_s, "try-error") || is.null(nuc_s)) {
        value <- rep(NA, n)
      } else {
        # Convert savings back to costs: x_i = v(i) - savings_i
        v_ind <- vvals[2^(1:n - 1)]
        value <- v_ind - nuc_s
      }
    }

    names(value) <- as.character(1:n)
    results <- list(value = value, nperms = "Not computed")

    # To display matrices C^T
    C_opt <- list()
    for (S in coalitions) {
      S_names <- paste0("S_", paste(S, collapse = ""))
      C_opt[[S_names]] <- C_T[[sum(2^(S - 1))]]
    }

  } else { # Monte Carlo (lazy evaluation)

    if (sol == "shapley") {
      # Skip full characteristic function for efficiency
      coals_names <- "Not computed (Lazy Monte Carlo)"
      values <- "Not computed (Lazy Monte Carlo)"
      C_opt <- "Not computed (Lazy Monte Carlo)"
      m_cost <- .get_cost(C_mat)

      # Initialize objects
      perms <- matrix(nrow = nsim, ncol = n)
      contributions <- matrix(0, nrow = nsim, ncol = n, dimnames = list(NULL, as.character(1:n)))

      for (p in 1:nsim) {
        pi <- sample(1:n)
        perms[p, ] <- pi
        predecessors <- integer(0)
        v_old <- 0

        for (i in pi) {
          predecessors <- c(predecessors, i)

          # Identify the complementary coalition for the current predecessors
          T_agents <- setdiff(1:n, predecessors)
          sub_idx <- c(1, predecessors + 1)
          T0_idx <- c(1, T_agents + 1)

          sub_C <- C_mat[sub_idx, sub_idx, drop = FALSE]

          # Apply the optimistic connection logic
          min_costs <- apply(C_mat[predecessors + 1, T0_idx, drop = FALSE], 1, min)

          cols <- 2:length(sub_idx)
          sub_C[1, cols] <- min_costs
          sub_C[cols, 1] <- min_costs

          v_new <- .get_cost(sub_C)
          contributions[p, as.character(i)] <- v_new - v_old
          v_old <- v_new
        }
      }

      # Results
      results <- list(
        value = colMeans(contributions),
        contributions = data.frame(pi = apply(perms, 1, paste, collapse = "-"),
                                   contributions, check.names = FALSE),
        nperms = nsim
      )
    }
  }


  ## Visualization ##

  if (draw) {

    show_details <- "details" %in% which.plot
    show_main <- "main" %in% which.plot

    if (n > 1 && n <= 3 && show_details && method == "exact") {

      rows <- if(n == 3) 2 else 1
      cols <- if(n == 3) 3 else 2
      old_par <- par(mfrow = c(rows, cols), oma = c(0, 0, if(titles) 5 else 0, 0))
      on.exit(par(old_par), add = TRUE)

      for (i in 1:(ncoals - 1)) {
        S <- coalitions[[i]]

        # Recalculate sub_C for visualization with modified source connections
        T_agents <- setdiff(1:n, S)
        sub_idx <- c(1, S + 1)
        T0_idx <- c(1, T_agents + 1)

        C_inf <- matrix(Inf, nrow = n + 1, ncol = n + 1, dimnames = list(0:n, 0:n))

        sub_C <- C_mat[sub_idx, sub_idx, drop = FALSE]

        min_costs <- apply(C_mat[S + 1, T0_idx, drop = FALSE], 1, min)
        cols_draw <- 2:length(sub_idx)
        sub_C[1, cols_draw] <- min_costs
        sub_C[cols_draw, 1] <- min_costs

        C_inf[sub_idx, sub_idx] <- sub_C
        arcs_S <- .get_arcs(sub_C)

        .plot_mcstp(C_inf, arcs_S, NULL,
                    main_title = "", sub_title = paste0("S = {", paste(S, collapse=","), "}"), show_stage = FALSE) #   |  v^o(S): ", round(values[i], 2)
      }

      if (titles) {
        mtext("MCST for each subcoalition S",
              side = 3, line = 1.5, cex = 1.2, font = 2, outer = TRUE)
        mtext("Optimistic Game (N, v^o)  |  Method: exact", side = 3, line = 0.1, cex = 0.7, family = "sans", font = 3,
              col = "#444444", outer = TRUE) # paste0("Optimistic Game  |  Total Cost v^o(N): ", round(m_cost, 2))
      }

      par(old_par)
    }

    if (n > 1 && n <= 3 && show_details && show_main && method == "exact") {
      devAskNewPage(TRUE)
      on.exit(devAskNewPage(FALSE), add = TRUE)
    }

    if (show_main) {
      arcs_N <- .get_arcs(C_mat)
      tit <- if(titles) "Optimistic Game (N, v^o)" else ""
      lab <- if (method == "exact") {"exact"} else {"Monte Carlo"}
      sol_name <- paste0(toupper(substr(sol, 1, 1)), substr(sol, 2, nchar(sol)))
      sub_tit <- if(titles) paste0("Solution: ", sol_name, "  |  Method: ", lab, "  |  Total Cost v^o(N): ", round(m_cost, 2)) else ""
      .plot_mcstp(C_mat, arcs_N, results$value,
                  main_title = tit, sub_title = sub_tit, show_stage = FALSE)
    }
  }

  # Generates a ranking based on allocations, using stars (*) for ties
  ord <- order(-results$value, names(results$value))
  vals <- results$value[ord]; noms <- names(results$value)[ord]
  tab <- table(vals)
  rep_vals <- sort(as.numeric(names(tab[tab > 1])), decreasing = TRUE)

  rank_star <- noquote(sapply(1:length(vals), function(i) {
    if (vals[i] %in% rep_vals) {
      paste0(noms[i], strrep("*", which(rep_vals == vals[i])))
    } else noms[i]
  }))


  ## Output ##

  output <- list(
    coalitions = coals_names,
    C_opt = C_opt,
    v_o = values,
    contributions = if(method == "montecarlo") results$contributions else "Exact method does not use a contributions table",
    allocation = results$value,
    total = m_cost,
    nperms = results$nperms,
    percentage = round((results$value / m_cost) * 100, 2),
    ranking = rank_star,
    method = method,
    sol = sol
  )

  class(output) <- "mcstp_opt"

  return(output)
}

#' @export
print.mcstp_opt <- function(x, ...) {
  if (is.character(x$v_o)) {
    cat("Characteristic function v^o(S) not computed (Monte Carlo efficiency mode)\n")
  } else {
    v_S <- data.frame(
      S = x$coalitions,
      "v^o(S)" = x$v_o,
      row.names = NULL,
      check.names = FALSE
    )
    print(v_S)
  }

  sol_label <- paste0(toupper(substr(x$sol, 1, 1)), substr(x$sol, 2, nchar(x$sol)))
  cat("\nSolution:", sol_label, "\n")
  print(round(x$allocation, 2))
  invisible(x)
}



#### Public Game ####

#' Cost Allocations based on the Public Game for MCSTP
#'
#' @description
#' This function computes the cost allocation for the public game
#' (Bogomolnaia and Moulin, 2010) associated with a minimum cost spanning tree problem
#' \eqn{(N_0, C)}, using a specified solution concept. The public game, denoted as \eqn{(N, v_C^u)} \eqn{(}or simply
#' \eqn{(N, v^u)}\eqn{)}, evaluates the cost of each coalition \eqn{S \subseteq N}
#' assuming that there are no property rights on nodes. Therefore, agents in
#' \eqn{S} can use the nodes of agents in \eqn{N \setminus S} to connect to
#' the source, paying the corresponding arc costs.
#'
#' @details
#' The public game \eqn{(N, v_C^u)} is a cooperative game with transferable
#' utility (TU game) where the cost for each coalition \eqn{S \subseteq N}
#' is defined as the minimum private game cost among all its supersets
#' \eqn{T \supseteq S}, i.e.:
#'
#' \deqn{v_C^u(S) = \min_{S \subseteq T} v_C^p(T),}
#'
#' where \eqn{v_C^p(\cdot)} is the characteristic function of the private game.
#' This means computing \eqn{v^u(S)} requires calculating the private game costs
#' for all possible supersets of \eqn{S}.
#'
#' Under \code{method = "exact"}, the function builds the full characteristic
#' function (all \eqn{2^n - 1} values). Depending on the chosen solution concept,
#' it computes the allocation via \code{\link[CoopGame]{shapleyValue}} (which
#' relies on the coalition-based formula) or \code{\link[CoopGame]{nucleolus}}.
#'
#' For larger networks, \code{method = "montecarlo"} provides an approximation
#' of the Shapley value through random sampling using \eqn{n_{sim}} permutations. This approach
#' implements lazy evaluation based on the permutation formula of the Shapley value:
#' instead of computing the MST cost for all \eqn{2^n - 1}
#' possible subsets, it only evaluates the specific subcoalitions generated by
#' the random permutations.
#'
#' This is highly useful when the number of agents is large,
#' as it significantly reduces memory usage and computation time while providing a
#' very accurate approximation of the exact allocation. For networks with few players, the
#' exact method is preferred to avoid potential overestimations.
#'
#' For more details on these formulas, see \code{\link{mcstRules}}.
#'
#' @inheritParams mcstGamePrivate
#'
#' @inheritSection mcstGamePrivate Supported formats for \code{C}
#'
#' @note
#' The core of \eqn{v^u} coincides with the core of \eqn{v^p} restricted
#' to nonnegative cost shares. Consequently, classical rules such as Bird,
#' Dutta-Kar, or the folk rule belong to the core of the public game
#' for any MCST problem.
#'
#' However, unlike in the private game, the Shapley value of the public game
#' does not necessarily belong to the core of \eqn{v^u} (Trudeau and Vidal-Puga, 2019).
#'
#' @return A list containing:
#' \itemize{
#'    \item \code{coalitions}: a character vector representing all possible coalitions \eqn{S \subseteq N}, ordered by cardinality. If \code{method = "montecarlo"}, returns a string indicating that lazy evaluation was used.
#'    \item \code{v_u}: a numeric vector containing the characteristic function values \eqn{v^u(S)} for all coalitions. If \code{method = "montecarlo"}, returns a string indicating that lazy evaluation was used.
#'    \item \code{v_p}: a numeric vector containing the characteristic function values \eqn{v^p(S)} for all coalitions. If \code{method = "montecarlo"}, returns a string indicating that lazy evaluation was used.
#'    \item \code{best_T}: a data frame mapping each coalition \eqn{S} to the optimal superset \eqn{T} that minimizes its cost. If \code{method = "montecarlo"}, returns a string indicating that lazy evaluation was used.
#'    \item \code{contributions}: a data frame with the marginal contributions for the sampled permutations. If \code{method = "exact"}, returns a string indicating that this table is not used.
#'    \item \code{allocation}: a numeric vector containing the computed cost allocation for each agent.
#'    \item \code{total}: the total cost of the MCST, \eqn{v^u(N)}.
#'    \item \code{nperms}: the number of permutations \code{nsim} used in the calculation. If \code{method = "exact"}, returns a string indicating that it was not computed.
#'    \item \code{percentage}: the share of the total cost allocated to each agent.
#'    \item \code{ranking}: ranking of agents by cost (from highest to lowest; ties marked with *).
#'    \item \code{method}: the method used for the calculation (\code{"exact"} or \code{"montecarlo"}).
#'    \item \code{sol}: the solution concept used (\code{"shapley"} or \code{"nucleolus"}).
#' }
#'
#' @seealso
#' \code{\link{mcstBird}}, \code{\link{mcstDuttaKar}}, \code{\link{mcstFolk}}
#' for classical rules belonging to the core of \eqn{v^u}.
#'
#' \code{\link{mcstGamePrivate}} for the pessimistic alternative to the public game.
#'
#' \code{\link{mcstGameIrred}} for a game that can be defined
#' from either the private or the public approach.
#'
#' \code{\link{mcstRules}} for an overview of the available rules and analysis tools in the package.
#'
#' @references
#' Bergantiños G, Vidal-Puga J (2021) A review of cooperative rules
#' and their associated algorithms for minimum-cost spanning tree problems.
#' SERIEs, 12:73-100
#'
#' Bogomolnaia A, Moulin H (2010) Sharing a minimal cost spanning tree:
#' beyond the folk solution. Games and Econom Behav 69(2):238–248
#'
#' Trudeau C, Vidal-Puga J (2019) The Shapley value in minimum cost
#' spanning tree problems. In: Algaba E, Fragnelli V, Sánchez-Soriano
#' J (eds) Chapters in Game Theory: The Shapley value, chapter 24.
#' CRC Press, Taylor & Francis Group
#'
#' @examples
#' # Simple vector input
#' mcstGamePublic(c(12, 15, 20, 4, 6, 8), sol = "shapley", draw = TRUE)
#'
#' # Input with infinite costs (disconnected nodes)
#' C_inf <- c(5, 9, Inf, 15, 6, Inf, 7, Inf, Inf, Inf,
#'            Inf, 8, 7, Inf, Inf, 5, Inf, Inf, 8, 9, 11)
#' mcstGamePublic(C_inf, sol = "shapley")
#'
#' # Matrix input
#' C_mat <- matrix(c(0, 12, 15, 12,
#'                  12,  0,  4,  6,
#'                  15,  4,  0,  8,
#'                  12,  6,  8,  0), byrow = TRUE, ncol = 4)
#' mcstGamePublic(C_mat, draw = TRUE, which.plot = "main", titles = FALSE)
#'
#' @concept Cooperative Games
#' @concept MCSTP
#'
#' @export

mcstGamePublic <- function(C, sol = c("shapley", "nucleolus"), draw = FALSE, which.plot = c("main", "details"), titles = TRUE, method = c("exact", "montecarlo"), nsim = 10000) {

  # Convert input into a standard cost matrix C for N_0 (agents + source)
  C_mat <- .prepare_matrix(C)
  n <- nrow(C_mat) - 1  # Number of agents n = |N|

  sol <- match.arg(sol)
  method <- match.arg(method)
  which.plot <- match.arg(which.plot, several.ok = TRUE)

  # Check if Monte Carlo is actually necessary
  if (sol == "shapley" && method == "montecarlo" && (2^n - 1) <= nsim) {
    message("Warning: (2^n - 1) <= nsim. Consider using method = 'exact' for maximum efficiency")
  }

  # Performance validation
  if (sol == "shapley" && method == "exact" && n > 20) {
    message("Warning: n > 20. Consider using method = 'montecarlo' to reduce processing time")
  }

  if (method == "montecarlo" && sol == "nucleolus") {
    stop("The solution '", sol, "' is only available for method = 'exact'")
  }

  if (sol == "nucleolus" && n > 15) {
    warning("Computing the nucleolus for n > 15 can be extremely slow and memory-intensive")
  }


  ## Execution ##

  if (method == "exact") { # Exact

    if (!requireNamespace("CoopGame", quietly = TRUE)) {
      stop("Package 'CoopGame' required for the exact method. Please install it.")
    }

    # Compute the private game values v^p(T) for all coalitions
    ncoals <- 2^n - 1

    vvals_p <- vapply(1:ncoals, function(i) {
      # Decode binary index i to find members of T
      T_set <- which(as.logical(intToBits(i)[1:n]))

      sub_idx <- c(1, T_set + 1) # Include the source (0)
      sub_C <- C_mat[sub_idx, sub_idx, drop = FALSE]
      .get_cost(sub_C)
    }, numeric(1))

    # Compute the public game values v^u(S)
    vvals <- numeric(ncoals)
    T_opt <- integer(ncoals) # To store the optimal superset T for drawing

    for (i in 1:ncoals) {
      # Find all supersets T of S
      supersets <- which(bitwAnd(1:ncoals, i) == i)

      # v^u(S) is the minimum v^p(T) among all supersets T
      min_idx <- supersets[which.min(vvals_p[supersets])]
      vvals[i] <- vvals_p[min_idx]
      T_opt[i] <- min_idx
    }

    # Generate all possible coalitions ordered by cardinality for final output
    coalitions <- unlist(lapply(1:n, function(k) combn(n, k, simplify = FALSE)), recursive = FALSE)
    coals_names <- sapply(coalitions, function(S) paste0("{", paste(S, collapse = ","), "}"))
    coals_names[length(coals_names)] <- "N"

    idx <- sapply(coalitions, function(S) sum(2^(S - 1)))
    values_p <- vvals_p[idx]
    values <- vvals[idx]
    m_cost <- vvals[ncoals] # Total cost v^u(N)

    # Calculate the allocation based on the chosen solution concept
    if (sol == "shapley") {
      value <- CoopGame::shapleyValue(values)

    } else if (sol == "nucleolus") {
      # Define savings game: v_s(S) = sum(v(i)) - v(S)
      v_s <- sapply(1:ncoals, function(i) {
        S <- which(as.logical(intToBits(i)[1:n]))
        sum(vvals[2^(S - 1)]) - vvals[i]
      })

      # Compute nucleolus of the savings game
      nuc_s <- try(CoopGame::nucleolus(v_s), silent = TRUE)

      if (inherits(nuc_s, "try-error") || is.null(nuc_s)) {
        value <- rep(NA, n)
      } else {
        # Convert savings back to costs: x_i = v(i) - savings_i
        v_ind <- vvals[2^(1:n - 1)]
        value <- v_ind - nuc_s
      }
    }

    names(value) <- as.character(1:n)
    results <- list(value = value, nperms = "Not computed")

    # Optimal superset for each coalition S for final output
    T_names <- character(ncoals)
    T_names[idx] <- coals_names

    # arg min_{ScT} v^p(T) for final output
    argmin_T <- T_names[T_opt[idx]]
    best_T <- data.frame(
      S = coals_names,
      T = as.character(argmin_T),
      row.names = NULL,
      check.names = FALSE
    )

  } else { # Monte Carlo (lazy evaluation)

    if (sol == "shapley") {
      # Skip full characteristic function for efficiency
      coals_names <- "Not computed (Lazy Monte Carlo)"
      values <- "Not computed (Lazy Monte Carlo)"
      values_p <- "Not computed (Lazy Monte Carlo)"
      best_T <- "Not computed (Lazy Monte Carlo)"
      m_cost <- .get_cost(C_mat)

      # Initialize objects
      perms <- matrix(nrow = nsim, ncol = n)
      contributions <- matrix(0, nrow = nsim, ncol = n, dimnames = list(NULL, as.character(1:n)))

      for (p in 1:nsim) {
        pi <- sample(1:n)
        perms[p, ] <- pi
        predecessors <- integer(0)
        v_old <- 0

        for (i in pi) {
          predecessors <- c(predecessors, i)

          # v^u(S) evaluates the minimum over all supersets T : ScT
          rem_agents <- setdiff(1:n, predecessors)
          n_rem <- length(rem_agents)

          if (n_rem == 0) {
            sub_idx <- c(1, predecessors + 1)
            v_new <- .get_cost(C_mat[sub_idx, sub_idx, drop = FALSE])
          } else {
            n_sub <- 2^n_rem - 1
            # Initial case where T is exactly the predecessors
            min_v <- .get_cost(C_mat[c(1, predecessors + 1), c(1, predecessors + 1), drop = FALSE])

            # Evaluate all possible supersets
            vals <- vapply(1:n_sub, function(k) {
              add_set <- rem_agents[which(as.logical(intToBits(k)[1:n_rem]))]
              T_set <- c(predecessors, add_set)
              sub_idx <- c(1, T_set + 1)
              .get_cost(C_mat[sub_idx, sub_idx, drop = FALSE])
            }, numeric(1))

            v_new <- min(min_v, vals)
          }

          contributions[p, as.character(i)] <- v_new - v_old
          v_old <- v_new
        }
      }

      # Results
      results <- list(
        value = colMeans(contributions),
        contributions = data.frame(pi = apply(perms, 1, paste, collapse = "-"),
                                   contributions, check.names = FALSE),
        nperms = nsim
      )
    }
  }


  ## Visualization ##

  if (draw) {

    show_details <- "details" %in% which.plot
    show_main <- "main" %in% which.plot

    if (n > 1 && n <= 3 && show_details && method == "exact") {

      rows <- if(n == 3) 2 else 1
      cols <- if(n == 3) 3 else 2
      old_par <- par(mfrow = c(rows, cols), oma = c(0, 0, if(titles) 5 else 0, 0))
      on.exit(par(old_par), add = TRUE)

      for (i in 1:(ncoals - 1)) {
        S <- coalitions[[i]]

        # We retrieve the optimal superset T that provided the minimum cost
        T_set <- which(as.logical(intToBits(T_opt[sum(2^(S - 1))])[1:n]))
        sub_idx <- c(1, T_set + 1)

        C_inf <- matrix(Inf, nrow = n + 1, ncol = n + 1, dimnames = list(0:n, 0:n))

        C_inf[sub_idx, sub_idx] <- C_mat[sub_idx, sub_idx]
        sub_C <- C_mat[sub_idx, sub_idx, drop = FALSE]
        arcs_T <- .get_arcs(sub_C)

        .plot_mcstp(C_inf, arcs_T, NULL,
                    main_title = "", sub_title = paste0("S = {", paste(S, collapse=","), "}"), show_stage = FALSE) #   |  v^u(S): ", round(values[i], 2)
      }

      if (titles) {
        mtext("MCST for each subcoalition S",
              side = 3, line = 1.5, cex = 1.2, font = 2, outer = TRUE)
        mtext("Public Game (N, v^u)  |  Method: exact", side = 3, line = 0.1, cex = 0.7, family = "sans", font = 3,
              col = "#444444", outer = TRUE) # paste0("Public Game  |  Total Cost v^u(N): ", round(m_cost, 2))
      }

      par(old_par)
    }

    if (n > 1 && n <= 3 && show_details && show_main && method == "exact") {
      devAskNewPage(TRUE)
      on.exit(devAskNewPage(FALSE), add = TRUE)
    }

    if (show_main) {
      arcs_N <- .get_arcs(C_mat)
      tit <- if(titles) "Public Game (N, v^u)" else ""
      lab <- if (method == "exact") {"exact"} else {"Monte Carlo"}
      sol_name <- paste0(toupper(substr(sol, 1, 1)), substr(sol, 2, nchar(sol)))
      sub_tit <- if(titles) paste0("Solution: ", sol_name, "  |  Method: ", lab, "  |  Total Cost v^u(N): ", round(m_cost, 2)) else ""
      .plot_mcstp(C_mat, arcs_N, results$value,
                  main_title = tit, sub_title = sub_tit, show_stage = FALSE)
    }
  }

  # Generates a ranking based on allocations, using stars (*) for ties
  ord <- order(-results$value, names(results$value))
  vals <- results$value[ord]; noms <- names(results$value)[ord]
  tab <- table(vals)
  rep_vals <- sort(as.numeric(names(tab[tab > 1])), decreasing = TRUE)

  rank_star <- noquote(sapply(1:length(vals), function(i) {
    if (vals[i] %in% rep_vals) {
      paste0(noms[i], strrep("*", which(rep_vals == vals[i])))
    } else noms[i]
  }))


  ## Output ##

  output <- list(
    coalitions = coals_names,
    v_u = values,
    v_p = values_p,
    best_T = best_T,
    contributions = if(method == "montecarlo") results$contributions else "Exact method does not use a contributions table",
    allocation = results$value,
    total = m_cost,
    nperms = results$nperms,
    percentage = round((results$value / m_cost) * 100, 2),
    ranking = rank_star,
    method = method,
    sol = sol
  )

  class(output) <- "mcstp_public"

  return(output)
}

#' @export
print.mcstp_public <- function(x, ...) {
  if (is.character(x$v_u)) {
    cat("Characteristic function v^u(S) not computed (Monte Carlo efficiency mode)\n")
  } else {
    v_S <- data.frame(
      S = x$coalitions,
      "v^u(S)" = x$v_u,
      row.names = NULL,
      check.names = FALSE
    )
    print(v_S)
  }

  sol_label <- paste0(toupper(substr(x$sol, 1, 1)), substr(x$sol, 2, nchar(x$sol)))
  cat("\nSolution:", sol_label, "\n")
  print(round(x$allocation, 2))
  invisible(x)
}



#### Cycle-complete Game ####

#' Cost Allocations based on the Cycle-complete Game for MCSTP
#'
#' @description
#' This function computes the cost allocation for the cycle-complete game
#' (Trudeau, 2012) associated with a minimum cost spanning tree problem \eqn{(N_0, C)}, using a specified solution concept. The
#' cycle-complete game, denoted as \eqn{(N, v_C^c)} \eqn{(}or simply \eqn{(N, v^c)}\eqn{)}, is
#' defined as the private game associated with the cycle-complete network
#' \eqn{(N_0, C^*)}.
#'
#' @details
#' The cycle-complete game \eqn{(N, v_C^c)} is a cooperative game with
#' transferable utility (TU game) defined for each coalition \eqn{S \subseteq N} as:
#'
#' \deqn{v_C^c(S) = m(S_0, C^*),}
#'
#' where \eqn{m(S_0, C^*)} is the cost of the minimum spanning tree of the
#' subproblem induced by the agents in \eqn{S} and the source, evaluated over
#' the cycle-complete costs \eqn{C^*}. The cycle-complete cost is defined as
#' the minimum between the direct cost \eqn{c_{ij}} and the smallest value of
#' the maximum arc cost over all cycles containing \eqn{i} and \eqn{j}, i.e.,
#' \eqn{c_{ij}^* = \min(c_{ij}, \min_{f \in \mathcal{C}(i,j)} \max_{e \in f} c_e),}
#' where \eqn{\mathcal{C}(i,j)} denotes the set of all cycles that include both \eqn{i} and \eqn{j}.
#'
#' For computational efficiency, \eqn{C^*} is obtained via
#' the irreducible matrices \eqn{\bar{C}} of the subgraphs as:
#'
#' \deqn{c_{ij}^* = \max_{k \in N \setminus \{i,j\}} {\bar{c}}_{ij}^{N \setminus \{k\}} \text{ for } i,j \in N,}
#'
#' and
#'
#' \deqn{c_{0i}^* = \max_{k \in N \setminus \{i\}} {\bar{c}}_{0i}^{N \setminus \{k\}} \text{ for } i \in N,}
#'
#' where \eqn{{\bar{C}}^{N \setminus \{k\}}} is the irreducible cost matrix of
#' the network excluding agent \eqn{k}. If no agents can be removed, the
#' irreducible cost of the full network is used.
#'
#' Under \code{method = "exact"}, the function builds the full characteristic
#' function (all \eqn{2^n - 1} values). Depending on the chosen solution concept,
#' it computes the allocation via \code{\link[CoopGame]{shapleyValue}} (called
#' \emph{cycle-complete solution}, which relies on the coalition-based formula)
#' or \code{\link[CoopGame]{nucleolus}}.
#'
#' For larger networks, \code{method = "montecarlo"} provides an approximation
#' of the Shapley value through random sampling using \eqn{n_{sim}} permutations. This approach
#' implements lazy evaluation based on the permutation formula of the Shapley value:
#' instead of computing the MST cost for all \eqn{2^n - 1}
#' possible subsets, it only evaluates the specific subcoalitions generated by
#' the random permutations.
#'
#' This is highly useful when the number of agents is large,
#' as it significantly reduces memory usage and computation time while providing a
#' very accurate approximation of the \emph{cycle-complete solution}. For networks with few players, the
#' exact method is preferred to avoid potential overestimations.
#'
#' For more details on these formulas, see \code{\link{mcstRules}}.
#'
#' @inheritParams mcstGamePrivate
#'
#' @inheritSection mcstGamePrivate Supported formats for \code{C}
#'
#' @note
#' The cycle-complete game is concave, which implies that its Shapley value
#' (the \emph{cycle-complete solution}) belongs to its core. Moreover,
#' \eqn{\mathrm{core}(N,v^c) \subseteq \mathrm{core}(N,v^p)}.
#'
#' @return A list containing:
#' \itemize{
#'    \item \code{coalitions}: a character vector representing all possible coalitions \eqn{S \subseteq N}, ordered by cardinality. If \code{method = "montecarlo"}, returns a string indicating that lazy evaluation was used.
#'    \item \code{C_cc}: the cycle-complete cost matrix \eqn{C^*}.
#'    \item \code{v_c}: a numeric vector containing the characteristic function values \eqn{v^c(S)} for all coalitions. If \code{method = "montecarlo"}, returns a string indicating that lazy evaluation was used.
#'    \item \code{contributions}: a data frame with the marginal contributions for the sampled permutations. If \code{method = "exact"}, returns a string indicating that this table is not used.
#'    \item \code{allocation}: a numeric vector containing the computed cost allocation for each agent.
#'    \item \code{total}: the total cost of the MCST, \eqn{v^c(N)}.
#'    \item \code{nperms}: the number of permutations \code{nsim} used in the calculation. If \code{method = "exact"}, returns a string indicating that it was not computed.
#'    \item \code{percentage}: the share of the total cost allocated to each agent.
#'    \item \code{ranking}: ranking of agents by cost (from highest to lowest; ties marked with *).
#'    \item \code{method}: the method used for the calculation (\code{"exact"} or \code{"montecarlo"}).
#'    \item \code{sol}: the solution concept used (\code{"shapley"} or \code{"nucleolus"}).
#' }
#'
#' @seealso
#' \code{\link{mcstGamePrivate}} for the pessimistic game based on the original costs.
#'
#' \code{\link{mcstGameIrred}} for the pessimistic game based on the irreducible cost matrix \eqn{\bar{C}}.
#'
#' \code{\link{mcstRules}} for an overview of the available rules and analysis tools in the package.
#'
#' @references
#' Bergantiños G, Vidal-Puga J (2021) A review of cooperative rules
#' and their associated algorithms for minimum-cost spanning tree problems.
#' SERIEs, 12:73-100
#'
#' Trudeau C (2012) A new stable and more responsible cost sharing solution
#' for mcst problems. Games Econom Behav 75(1):402–412
#'
#' @examples
#' # Simple vector input
#' mcstGameCC(c(12, 15, 20, 4, 6, 8), sol = "shapley", draw = TRUE)
#'
#' # Input with infinite costs (disconnected nodes)
#' C_inf <- c(5, 9, Inf, 15, 6, Inf, 7, Inf, Inf, Inf,
#'            Inf, 8, 7, Inf, Inf, 5, Inf, Inf, 8, 9, 11)
#' mcstGameCC(C_inf, sol = "shapley")
#'
#' # Matrix input
#' C_mat <- matrix(c(0, 12, 15, 12,
#'                  12,  0,  4,  6,
#'                  15,  4,  0,  8,
#'                  12,  6,  8,  0), byrow = TRUE, ncol = 4)
#' mcstGameCC(C_mat, draw = TRUE, which.plot = "main", titles = FALSE)
#'
#' @concept Cooperative Games
#' @concept MCSTP
#'
#' @export

mcstGameCC <- function(C, sol = c("shapley", "nucleolus"), draw = FALSE, which.plot = c("main", "details"), titles = TRUE, method = c("exact", "montecarlo"), nsim = 10000) {

  # Convert input into a standard cost matrix C for N_0 (agents + source)
  C_mat <- .prepare_matrix(C)
  n <- nrow(C_mat) - 1  # Number of agents n = |N|

  sol <- match.arg(sol)
  method <- match.arg(method)
  which.plot <- match.arg(which.plot, several.ok = TRUE)

  # Check if Monte Carlo is actually necessary
  if (sol == "shapley" && method == "montecarlo" && (2^n - 1) <= nsim) {
    message("Warning: (2^n - 1) <= nsim. Consider using method = 'exact' for maximum efficiency")
  }

  # Performance validation
  if (sol == "shapley" && method == "exact" && n > 20) {
    message("Warning: n > 20. Consider using method = 'montecarlo' to reduce processing time")
  }

  if (method == "montecarlo" && sol == "nucleolus") {
    stop("The solution '", sol, "' is only available for method = 'exact'")
  }

  if (sol == "nucleolus" && n > 15) {
    warning("Computing the nucleolus for n > 15 can be extremely slow and memory-intensive")
  }


  ## Execution ##

  # Compute the cycle-complete matrix C*
  C_cc <- .get_cycle_complete(C_mat)

  if (method == "exact") { # Exact

    if (!requireNamespace("CoopGame", quietly = TRUE)) {
      stop("Package 'CoopGame' required for the exact method. Please install it.")
    }

    # Build the characteristic function v^c(S) using binary indexing over C*
    ncoals <- 2^n - 1

    vvals <- vapply(1:ncoals, function(i) {
      # Decode binary index i to find members of coalition S
      S <- which(as.logical(intToBits(i)[1:n]))
      sub_idx <- c(1, S + 1) # Include the source (0)

      # Compute MST cost for this specific subset
      .get_cost(C_cc[sub_idx, sub_idx, drop = FALSE])
    }, numeric(1))

    # Generate all possible coalitions ordered by cardinality for final output
    coalitions <- unlist(lapply(1:n, function(k) combn(n, k, simplify = FALSE)), recursive = FALSE)
    coals_names <- sapply(coalitions, function(S) paste0("{", paste(S, collapse = ","), "}"))
    coals_names[length(coals_names)] <- "N"

    idx <- sapply(coalitions, function(S) sum(2^(S - 1)))
    values <- vvals[idx]
    m_cost <- vvals[ncoals] # Total cost v^c(N)

    # Calculate the allocation based on the chosen solution concept
    if (sol == "shapley") {
      value <- CoopGame::shapleyValue(values)

    } else if (sol == "nucleolus") {
      # Define savings game: v_s(S) = sum(v(i)) - v(S)
      v_s <- sapply(1:ncoals, function(i) {
        S <- which(as.logical(intToBits(i)[1:n]))
        sum(vvals[2^(S - 1)]) - vvals[i]
      })

      # Compute nucleolus of the savings game
      nuc_s <- try(CoopGame::nucleolus(v_s), silent = TRUE)

      if (inherits(nuc_s, "try-error") || is.null(nuc_s)) {
        value <- rep(NA, n)
      } else {
        # Convert savings back to costs: x_i = v(i) - savings_i
        v_ind <- vvals[2^(1:n - 1)]
        value <- v_ind - nuc_s
      }
    }

    names(value) <- as.character(1:n)
    results <- list(value = value, nperms = "Not computed")

  } else { # Monte Carlo (lazy evaluation)

    if (sol == "shapley") {
      # Skip full characteristic function for efficiency
      coals_names <- "Not computed (Lazy Monte Carlo)"
      values <- "Not computed (Lazy Monte Carlo)"
      m_cost <- .get_cost(C_cc)

      # Initialize objects
      perms <- matrix(nrow = nsim, ncol = n)
      contributions <- matrix(0, nrow = nsim, ncol = n, dimnames = list(NULL, as.character(1:n)))

      for (p in 1:nsim) {
        pi <- sample(1:n)
        perms[p, ] <- pi
        predecessors <- c()
        v_old <- 0

        for (i in pi) {
          predecessors <- c(predecessors, i)
          sub_idx <- c(1, predecessors + 1)
          v_new <- .get_cost(C_cc[sub_idx, sub_idx, drop = FALSE])
          contributions[p, i] <- v_new - v_old
          v_old <- v_new
        }
      }

      # Results
      results <- list(
        value = colMeans(contributions),
        contributions = data.frame(pi = apply(perms, 1, paste, collapse = "-"),
                                   contributions, check.names = FALSE),
        nperms = nsim
      )
    }
  }


  ## Visualization ##

  if (draw) {

    show_details <- "details" %in% which.plot
    show_main <- "main" %in% which.plot

    if (n > 1 && n <= 3 && show_details && method == "exact") {

      rows <- if(n == 3) 2 else 1
      cols <- if(n == 3) 3 else 2
      old_par <- par(mfrow = c(rows, cols), oma = c(0, 0, if(titles) 5 else 0, 0))
      on.exit(par(old_par), add = TRUE)

      for (i in 1:(ncoals - 1)) {
        S <- coalitions[[i]]
        sub_idx <- c(1, S + 1)

        C_inf <- matrix(Inf, nrow = n + 1, ncol = n + 1, dimnames = list(0:n, 0:n))

        C_inf[sub_idx, sub_idx] <- C_cc[sub_idx, sub_idx]
        sub_C <- C_cc[sub_idx, sub_idx, drop = FALSE]
        arcs_S <- .get_arcs(sub_C)

        .plot_mcstp(C_inf, arcs_S, NULL,
                    main_title = "", sub_title = paste0("S = {", paste(S, collapse=","), "}"), show_stage = FALSE) #   |  v^c(S): ", round(values[i], 2)
      }

      if (titles) {
        mtext("MCST for each subcoalition S",
              side = 3, line = 1.5, cex = 1.2, font = 2, outer = TRUE)
        mtext("Cycle-complete Game (N, v^c)  |  Method: exact", side = 3, line = 0.1, cex = 0.7, family = "sans", font = 3,
              col = "#444444", outer = TRUE) # paste0("Cycle-complete Game  |  Total Cost v^c(N): ", round(m_cost, 2))
      }

      par(old_par)
    }

    if (n > 1 && n <= 3 && show_details && show_main && method == "exact") {
      devAskNewPage(TRUE)
      on.exit(devAskNewPage(FALSE), add = TRUE)
    }

    if (show_main) {
      arcs_N <- .get_arcs(C_cc)
      tit <- if(titles) "Cycle-complete Game (N, v^c)" else ""
      lab <- if (method == "exact") {"exact"} else {"Monte Carlo"}
      sol_name <- paste0(toupper(substr(sol, 1, 1)), substr(sol, 2, nchar(sol)))
      sub_tit <- if(titles) paste0("Solution: ", sol_name, "  |  Method: ", lab, "  |  Total Cost v^c(N): ", round(m_cost, 2)) else ""
      .plot_mcstp(C_cc, arcs_N, results$value,
                  main_title = tit, sub_title = sub_tit, show_stage = FALSE)
    }
  }

  # Generates a ranking based on allocations, using stars (*) for ties
  ord <- order(-results$value, names(results$value))
  vals <- results$value[ord]; noms <- names(results$value)[ord]
  tab <- table(vals)
  rep_vals <- sort(as.numeric(names(tab[tab > 1])), decreasing = TRUE)

  rank_star <- noquote(sapply(1:length(vals), function(i) {
    if (vals[i] %in% rep_vals) {
      paste0(noms[i], strrep("*", which(rep_vals == vals[i])))
    } else noms[i]
  }))


  ## Output ##

  output <- list(
    coalitions = coals_names,
    C_cc = C_cc,
    v_c = values,
    contributions = if(method == "montecarlo") results$contributions else "Exact method does not use a contributions table",
    allocation = results$value,
    total = m_cost,
    nperms = results$nperms,
    percentage = round((results$value / m_cost) * 100, 2),
    ranking = rank_star,
    method = method,
    sol = sol
  )

  class(output) <- "mcstp_cc"

  return(output)
}

#' @export
print.mcstp_cc <- function(x, ...) {
  if (is.character(x$v_c)) {
    cat("Characteristic function v^c(S) not computed (Monte Carlo efficiency mode)\n")
  } else {
    v_S <- data.frame(
      S = x$coalitions,
      "v^c(S)" = x$v_c,
      row.names = NULL,
      check.names = FALSE
    )
    print(v_S)
  }

  sol_label <- paste0(toupper(substr(x$sol, 1, 1)), substr(x$sol, 2, nchar(x$sol)))
  cat("\nSolution:", sol_label, "\n")
  print(round(x$allocation, 2))
  invisible(x)
}



# Modified 12/05 21:00
